#!/usr/bin/env python
import sys
from subprocess import Popen
import pkg_resources


def main():
    server_executable = pkg_resources.resource_filename('{{package.name}}', 'bin/rest-proxy-server.bin')
    proc = Popen([server_executable] + sys.argv[1:])

    return_code = 0
    try:
        return_code = proc.wait()
    except Exception:
        return_code = proc.terminate()

    raise SystemExit(return_code)


if __name__ == '__main__':
    main()
